In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score 

In [3]:
forecast = pd.read_csv("data_forecast_TN.csv")
forecast

Date    NYC_CPI          RUT        VIX     Silver         WTI  \
0    2022-08-17  27.116701  2243.775595  22.294036  20.317591   99.818871   
1    2022-08-18  27.120365  2244.032444  22.183190  20.260996  100.011986   
2    2022-08-19  27.126677  2244.356533  22.902694  20.203477  100.154258   
3    2022-08-20  26.867031  2246.449835  22.847423  20.097197  104.438615   
4    2022-08-21  27.109861  2247.601304  22.941220  19.456680  104.611137   
..          ...        ...          ...        ...        ...         ...   
725  2024-08-11  26.881988  2788.346399  20.279163   9.896198  158.652107   
726  2024-08-12  26.912686  2790.328858  20.424958  10.464064  154.346536   
727  2024-08-13  26.915964  2791.483927  20.312915  10.399755  154.636302   
728  2024-08-14  26.924106  2794.745798  20.383456  10.304101  154.615017   
729  2024-08-15  26.927659  2794.777429  20.501411  10.241630  154.763474   

             NDX          DJI       S&P500    TN  
0    15325.39448  36096.52704  4684.945851  2.25  
1    15340.26265  36114.99106  4688.209908  2.25  
2    15353.16563  36139.98492  4691.927255  2.25  
3    15418.87586  36365.88872  4712.983802  2.25  
4    15438.05433  36386.80534  4716.758857  2.25  
..           ...          ...          ...   ...  
725  19720.52209  43738.17960  5936.455120  2.50  
726  19699.64594  43543.90550  5922.320409  2.50  
727  19716.49912  43573.75497  5926.266377  2.50  
728  19738.07922  43582.76365  5929.351743  2.50  
729  19752.22016  43599.65525  5932.396911  2.50  

[730 rows x 10 columns]

In [4]:
date = forecast[['Date']]
date

Date
0    2022-08-17
1    2022-08-18
2    2022-08-19
3    2022-08-20
4    2022-08-21
..          ...
725  2024-08-11
726  2024-08-12
727  2024-08-13
728  2024-08-14
729  2024-08-15

[730 rows x 1 columns]

In [5]:
forecast = forecast[['NYC_CPI','RUT','VIX','Silver','WTI','NDX','DJI','S&P500','TN']]
forecast

NYC_CPI          RUT        VIX     Silver         WTI          NDX  \
0    27.116701  2243.775595  22.294036  20.317591   99.818871  15325.39448   
1    27.120365  2244.032444  22.183190  20.260996  100.011986  15340.26265   
2    27.126677  2244.356533  22.902694  20.203477  100.154258  15353.16563   
3    26.867031  2246.449835  22.847423  20.097197  104.438615  15418.87586   
4    27.109861  2247.601304  22.941220  19.456680  104.611137  15438.05433   
..         ...          ...        ...        ...         ...          ...   
725  26.881988  2788.346399  20.279163   9.896198  158.652107  19720.52209   
726  26.912686  2790.328858  20.424958  10.464064  154.346536  19699.64594   
727  26.915964  2791.483927  20.312915  10.399755  154.636302  19716.49912   
728  26.924106  2794.745798  20.383456  10.304101  154.615017  19738.07922   
729  26.927659  2794.777429  20.501411  10.241630  154.763474  19752.22016   

             DJI       S&P500    TN  
0    36096.52704  4684.945851  2.25  
1    36114.99106  4688.209908  2.25  
2    36139.98492  4691.927255  2.25  
3    36365.88872  4712.983802  2.25  
4    36386.80534  4716.758857  2.25  
..           ...          ...   ...  
725  43738.17960  5936.455120  2.50  
726  43543.90550  5922.320409  2.50  
727  43573.75497  5926.266377  2.50  
728  43582.76365  5929.351743  2.50  
729  43599.65525  5932.396911  2.50  

[730 rows x 9 columns]

In [8]:
gold_price_USD = pd.read_csv("gold_price_USD_TN.csv")

In [10]:
gold_price_USD = gold_price_USD.drop(['Date'], axis=1)

In [11]:
gold_price_USD

United States(USD)  NYC_CPI      RUT    VIX  Silver    WTI       NDX  \
0                1078.5    25.05   602.04  24.62  16.183  78.40  14672.68   
1                1108.3    25.03   628.56  19.50  16.500  76.45  14503.95   
2                1115.5    24.97   678.64  17.59  17.512  81.29  13748.74   
3                1179.3    24.94   716.60  22.05  18.611  84.58  13962.68   
4                1207.5    25.09   661.61  32.07  18.411  74.12  13246.87   
..                  ...      ...      ...    ...     ...    ...       ...   
134              1691.1    27.13  2220.52  19.40  24.532  62.36   2257.04   
135              1767.7    27.30  2266.45  18.61  25.915  61.70   2461.19   
136              1900.0    27.36  2268.97  16.76  28.014  65.16   2397.96   
137              1763.2    27.40  2310.55  15.83  26.194  71.35   2238.26   
138              1825.8    27.51  2226.25  18.24  25.547  72.43   2147.35   

          DJI   S&P500   T/N  
0    34935.47  4395.26  3.58  
1    34502.51  4297.50  3.61  
2    34529.45  4204.11  3.83  
3    33874.85  4181.17  3.65  
4    32981.55  3972.89  3.29  
..        ...      ...   ...  
134  10136.63  1089.41  1.74  
135  11008.61  1186.69  1.63  
136  10856.63  1169.43  1.59  
137  10325.26  1104.49  1.47  
138  10067.33  1073.87  1.23  

[139 rows x 10 columns]

In [15]:
y = gold_price_USD["United States(USD)"]
X = gold_price_USD.drop(["United States(USD)"], axis =1, inplace=False)

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.3, random_state=1)

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
y_preds = lr_model.predict(X_test)

mse = mean_squared_error(y_test, y_preds)

mse

2344.024590499058

In [16]:
from sklearn.linear_model import Ridge, Lasso

Ri_model = Ridge()

Ri_model.fit(X_train, y_train)
print(f"릿지회귀 적용 : {Ri_model.score(X_train, y_train)}, {Ri_model.score(X_test, y_test)}")

La_model = Lasso()

La_model.fit(X_train, y_train)
print(f"라쏘회귀 적용 : {La_model.score(X_train, y_train)}, {La_model.score(X_test, y_test)}")

릿지회귀 적용 : 0.947810247856688, 0.9513144419194748
라쏘회귀 적용 : 0.9479092130724597, 0.9534965986378386


C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.618e+05, tolerance: 5.333e+02
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive


In [18]:
predict = []
for i in range(0,730):
    a = forecast.iloc[[i]]
    b = La_model.predict(a)
    predict.append(b)
    #print(f"예측{i},{b}")

predict

C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message, FutureWarning)
C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message, FutureWarning)
C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message

C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message, FutureWarning)
C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message, FutureWarning)
C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message

C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message, FutureWarning)
C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message, FutureWarning)
C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message

C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message, FutureWarning)
C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message, FutureWarning)
C:\Users\gjaischool\.conda\envs\gold\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- TN
Feature names seen at fit time, yet now missing:
- T/N

  warnings.warn(message

[array([1726.66286021]),
 array([1725.19113063]),
 array([1729.08816307]),
 array([1717.81354359]),
 array([1720.80060821]),
 array([1730.2178058]),
 array([1729.92774709]),
 array([1730.5605101]),
 array([1731.13960649]),
 array([1734.4272811]),
 array([1723.64581019]),
 array([1727.023323]),
 array([1736.70267089]),
 array([1736.52408731]),
 array([1737.09920719]),
 array([1737.43762988]),
 array([1740.29270445]),
 array([1728.88316884]),
 array([1731.43915055]),
 array([1740.11108121]),
 array([1738.75221894]),
 array([1737.99239092]),
 array([1736.8641298]),
 array([1738.14789325]),
 array([1725.09301861]),
 array([1725.96293952]),
 array([1732.94323635]),
 array([1729.92323901]),
 array([1727.56882473]),
 array([1724.94760052]),
 array([1724.87320257]),
 array([1710.62536717]),
 array([1710.49435787]),
 array([1716.68829756]),
 array([1713.11420386]),
 array([1710.45031207]),
 array([1707.77095855]),
 array([1707.89072452]),
 array([1694.08450365]),
 array([1694.63208213]),
 array

In [19]:
df = pd.DataFrame(predict, columns = ['gold_price'])
df

gold_price
0    1726.662860
1    1725.191131
2    1729.088163
3    1717.813544
4    1720.800608
..           ...
725  1535.493535
726  1544.317492
727  1543.337194
728  1543.216273
729  1543.014678

[730 rows x 1 columns]

In [20]:
gold = pd.concat([date, df], axis = 1)
gold

Date   gold_price
0    2022-08-17  1726.662860
1    2022-08-18  1725.191131
2    2022-08-19  1729.088163
3    2022-08-20  1717.813544
4    2022-08-21  1720.800608
..          ...          ...
725  2024-08-11  1535.493535
726  2024-08-12  1544.317492
727  2024-08-13  1543.337194
728  2024-08-14  1543.216273
729  2024-08-15  1543.014678

[730 rows x 2 columns]

In [78]:
gold.to_csv("la_gold.csv", index=False)

In [35]:
ri = []
for i in range(0,730):
    a = forecast.iloc[[i]]
    b = Ri_model.predict(a)
    ri.append(b)
    #print(f"예측{i},{b}")

ri

[array([1710.99807076]),
 array([1709.44420242]),
 array([1713.29193894]),
 array([1701.35758345]),
 array([1704.28906961]),
 array([1714.24843189]),
 array([1713.86481227]),
 array([1714.41239957]),
 array([1714.89497675]),
 array([1718.1159567]),
 array([1706.66335875]),
 array([1709.97757917]),
 array([1720.19534221]),
 array([1719.92363144]),
 array([1720.4183357]),
 array([1720.66938614]),
 array([1723.47127446]),
 array([1711.40836758]),
 array([1713.92285691]),
 array([1723.15875732]),
 array([1721.73570378]),
 array([1720.9273268]),
 array([1719.74597096]),
 array([1721.01265668]),
 array([1707.34172206]),
 array([1708.20800016]),
 array([1715.78996798]),
 array([1712.74263802]),
 array([1710.37500368]),
 array([1707.73381934]),
 array([1707.67265671]),
 array([1692.83567684]),
 array([1692.72403213]),
 array([1699.53830798]),
 array([1695.95085861]),
 array([1693.28278541]),
 array([1690.58742455]),
 array([1690.71925255]),
 array([1676.31765652]),
 array([1676.87348845]),
 ar

In [22]:
RI = pd.DataFrame(ri, columns = ['gold_price'])
RI

gold_price
0    1710.998071
1    1709.444202
2    1713.291939
3    1701.357583
4    1704.289070
..           ...
725  1495.059088
726  1504.457975
727  1503.415588
728  1503.239035
729  1502.967904

[730 rows x 1 columns]

In [23]:
ri_gold = pd.concat([date, RI], axis = 1)
ri_gold

Date   gold_price
0    2022-08-17  1710.998071
1    2022-08-18  1709.444202
2    2022-08-19  1713.291939
3    2022-08-20  1701.357583
4    2022-08-21  1704.289070
..          ...          ...
725  2024-08-11  1495.059088
726  2024-08-12  1504.457975
727  2024-08-13  1503.415588
728  2024-08-14  1503.239035
729  2024-08-15  1502.967904

[730 rows x 2 columns]

In [31]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [76]:
from sklearn.linear_model import Lasso, ElasticNet

elastic_alphas = [0.07, 0.1, 0.5, 1, 3]
coeff_elastic_df = get_linear_reg_eval('ElasticNet', params=elastic_alphas, X_data_n = X, y_target_n = y)


### ElasticNet ####
alpha 0.07일 때 5 폴드 세트의 평균 RMSE: 160.403
alpha 0.1일 때 5 폴드 세트의 평균 RMSE: 158.139
alpha 0.5일 때 5 폴드 세트의 평균 RMSE: 160.162
alpha 1일 때 5 폴드 세트의 평균 RMSE: 164.256
alpha 3일 때 5 폴드 세트의 평균 RMSE: 165.927


In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.1,random_state=42)
y_preds = elastic_net.predict(X_test)
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.1, random_state=1)
elastic_net.fit(X, y)
print(f"ElasticNet : {elastic_net.score(X_train, y_train)}, {elastic_net.score(X_test, y_test)}")

ElasticNet : 0.9418854448801213, 0.9270655577318886


In [38]:
sort_column = 'alpha:'+str(elastic_alphas[0])
coeff_elastic_df.sort_values(by=sort_column, ascending=False)

alpha:0.07   alpha:0.1  alpha:0.5    alpha:1    alpha:3
NYC_CPI   45.262888   40.744813  15.945513   7.918563   1.068785
Silver    20.598323   20.777318  22.261658  23.020975  23.572824
VIX        6.183946    6.187108   6.508736   6.815779   7.222755
RUT        0.203941    0.204002   0.201210   0.197902   0.191627
NDX        0.084351    0.084272   0.082503   0.081260   0.081045
DJI        0.068139    0.071059   0.091627   0.101506   0.113772
WTI        0.030067   -0.120959  -1.241718  -1.791882  -2.381238
S&P500    -0.797166   -0.825044  -1.014350  -1.102363  -1.214632
T/N     -137.568900 -131.351835 -82.026833 -55.722594 -24.021329

In [29]:
def get_linear_reg_eval(model_name, params=None, X_data_n=None, y_target_n=None,
                        verbose=True, return_coeff=True):
    coeff_df = pd.DataFrame()
    if verbose : print("###", model_name, "####")
    
    for param in params:
        if model_name == 'Ridge' : model = Ridge(alpha=param)
        elif model_name == 'Lasso' : model = Lasso(alpha=param)
        elif model_name == 'ElasticNet' : model = ElasticNet(alpha=param, l1_ratio=0.7)
            
        neg_mse_scores = cross_val_score(model, X_data_n,
                                        y_target_n, scoring="neg_mean_squared_error", cv = 5)
        avg_rmse = np.mean(np.sqrt(-1 * neg_mse_scores))
        
        print("alpha {0}일 때 5 폴드 세트의 평균 RMSE: {1:.3f}".format(param, avg_rmse))
        
        model.fit(X_data_n, y_target_n)
        
        if return_coeff:
            coeff = pd.Series(data=model.coef_, index=X_data_n.columns)
            colname='alpha:'+str(param)
            coeff_df[colname]=coeff
            
    return coeff_df

In [34]:
elastic_alphas = [0.07, 0.1, 0.5, 1, 3]
coeff_elastic_df = get_linear_reg_eval('ElasticNet', params=elastic_alphas, X_data_n = X, y_target_n = y)

### ElasticNet ####
alpha 0.07일 때 5 폴드 세트의 평균 RMSE: 160.403
alpha 0.1일 때 5 폴드 세트의 평균 RMSE: 158.139
alpha 0.5일 때 5 폴드 세트의 평균 RMSE: 160.162
alpha 1일 때 5 폴드 세트의 평균 RMSE: 164.256
alpha 3일 때 5 폴드 세트의 평균 RMSE: 165.927


In [75]:
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.1, random_state=1)
elastic_net.fit(X, y)

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.1,random_state=42)
y_preds = elastic_net.predict(X_test)
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.1, random_state=1)
elastic_net.fit(X, y)
print(f"ElasticNet : {elastic_net.score(X_train, y_train)}, {elastic_net.score(X_test, y_test)}")

ElasticNet : 0.9418854448801213, 0.9270655577318886


In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.1,random_state=42)
y_preds = elastic_net.predict(X_test)
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.1, random_state=1)
elastic_net.fit(X, y)
print(f"ElasticNet : {elastic_net.score(X_train, y_train)}, {elastic_net.score(X_test, y_test)}")

ElasticNet : 0.9418854448801213, 0.9270655577318886


In [70]:
elastic_net = ElasticNet(alpha=0.07, l1_ratio=0.1, random_state=42)
elastic_net.fit(X, y)
print(f"ElasticNet : {elastic_net.score(X_train, y_train)}, {elastic_net.score(X_test, y_test)}")

ElasticNet : 0.945657857684632, 0.9321337987424947


In [71]:
elastic_net = ElasticNet(alpha=0.5, l1_ratio=0.1, random_state=42)
elastic_net.fit(X, y)
print(f"ElasticNet : {elastic_net.score(X_train, y_train)}, {elastic_net.score(X_test, y_test)}")

ElasticNet : 0.9088365564223373, 0.8934758079993824


In [72]:
elastic_net = ElasticNet(alpha=1, l1_ratio=0.1, random_state=42)
elastic_net.fit(X, y)
print(f"ElasticNet : {elastic_net.score(X_train, y_train)}, {elastic_net.score(X_test, y_test)}")

ElasticNet : 0.8938885893983023, 0.8800483576373923


In [73]:
elastic_net = ElasticNet(alpha=3, l1_ratio=0.1, random_state=42)
elastic_net.fit(X, y)
print(f"ElasticNet : {elastic_net.score(X_train, y_train)}, {elastic_net.score(X_test, y_test)}")

ElasticNet : 0.877134761540272, 0.8642253428500141
